MvcProject/Controllers/AuthorizationController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    [AllowAnonymous]
    public class AuthorizationController : Controller
    {
        // GET: Authorization
        AdminManager adminManager = new AdminManager(new EfAdminDal());
        public ActionResult Index()
        {
            var adminvalue = adminManager.GetListAdmin();
            return View(adminvalue);
        }
        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            SHA1 sha1 = new SHA1CryptoServiceProvider();
            string password = p.AdminPassword;
            string result = Convert.ToBase64String(sha1.ComputeHash(Encoding.UTF8.GetBytes(password)));
            p.AdminPassword = result;
            adminManager.Add(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            var adminvalue = adminManager.GetById(id);
            return View(adminvalue);
        }
        [HttpPost]
        public ActionResult EditAdmin(Admin p)
        {
            adminManager.Update(p);
            return RedirectToAction("Index");

        }
    }
}

MvcProject/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<h1>Yeni ADmin Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Admin Adı")
    @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
    <br /> <br />
    @Html.Label("Şifreyi Giriniz")
    @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
    <br /> <br />
    @Html.Label("Rolü Giriniz")
    @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
    <br /> <br />
    <button id="btn2">Kaydet</button>
</div>
}

MvcProject/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Admin Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })
    <br />
    @Html.Label("Admin Adı")
    @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
    <br />
    @Html.Label("Admin Şifresi")
    @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
    <br />
    @Html.Label("Admin Rolü")
    @*@Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.valueAdmin, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.AdminRole, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />


    <button class="btn btn-success">Güncelle</button>
</div>
}

MvcProject/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-">
    <tr>
        <th>Kullanıcı Adı</th>
        <th>Yetki</th>
        <th>Durum</th>
        <th>Yetki Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AdminUserName</td>
            @*<td>@item.Role.RoleName</td>*@
            <td>Aktif</td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
        </tr>
    }
</table>
<a href="/Authorization/AddAdmin/" class="btn btn-success">Admin Ekle</a>